config/routes.rb
Rails.application.routes.draw do
  resources :arts

  root 'arts#index'

  get '/authorize' => 'arts#authorize'

end

app/models/art.rb
class Art < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  def authorize

      gon.code = params[:code]
      #pass in the code to get the access token
      gon.access_token_response = HTTParty.get("https://www.deviantart.com/oauth2/token?"+
      "grant_type=authorization_code&"+
      "client_id=1479&"+
      "client_secret=ff642ac312683d522fedcb531330d5a0&"+
      "code="+gon.code.to_s+"&"+
      "redirect_uri=http://wallflower.herokuapp.com/authorize"
      )

      #pass in the access token to get the username
      gon.username_response = HTTParty.get("https://www.deviantart.com/api/v1/oauth2/user/whoami?"+"access_token="+gon.access_token_response["access_token"].to_s)

      #pass in the username to access favorites
      redirect_to("http://"+gon.username_response["username"]+".deviantart.com/favourites/?"+"access_token="+gon.access_token_response["access_token"].to_s)
  end

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params[:art]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<script>
  var url = 'http://www.deviantart.com/art/Pokemon-Officer-Jenny-01-461937344'
  var oembed_url = 'http://backend.deviantart.com/oembed?url='+url+'&format=jsonp&callback=?';
  $.getJSON(oembed_url, function(data) {
    console.log('Deviation by: ' + data.author_name);
  $("#my_image").attr("src",data.url);
  });
</script>

<a href="https://www.deviantart.com/oauth2/authorize?
response_type=code&client_id=1479&redirect_uri=http://wallflower.herokuapp.com/authorize">Login</a>

<img id="my_image" src="">

<h1>Listing arts TEST</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td><%= link_to 'Show', art %></td>
        <td><%= link_to 'Edit', edit_art_path(art) %></td>
        <td><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Art', new_art_path %>

app/views/arts/new.html.erb
<h1>New art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallflower</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>

<%= yield %>

</body>
</html>